# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  clyde-orderer.clyde.com.au:
    container_name: clyde-orderer.clyde.com.au
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=127.0.0.1
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Clyde-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - clyde-orderer.clyde.com.au:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.producer.com.au:
    container_name: peer0.producer.com.au
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.com.au
      - CORE_PEER_ADDRESS=peer0.producer.com.au:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.com.au:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.com.au:7051
      - CORE_PEER_LOCALMSPID=Producer-MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.com.au/peers/peer0.producer.com.au/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.com.au/peers/peer0.producer.com.au/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.com.au:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.producer.com.au:
    container_name: peer1.producer.com.au
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.producer.com.au
      - CORE_PEER_ADDRESS=peer1.producer.con.au:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.com.au:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.com.au:7051
      - CORE_PEER_LOCALMSPID=Producer-MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.com.au/peers/peer1.producer.com.au/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.com.au/peers/peer1.producer.com.au/tls:/etc/hyperledger/fabric/tls
        - peer1.producer.com.au:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.consumer.com.au:
    container_name: peer0.consumer.com.au
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.com.au
      - CORE_PEER_ADDRESS=peer0.consumer.com.au:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.com.au:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.com.au:7051
      - CORE_PEER_LOCALMSPID=Consumer-MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.com.au/peers/peer0.consumer.com.au/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.com.au/peers/peer0.consumer.com.au/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.com.au:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.consumer.com.au:
    container_name: peer1.consumer.com.au
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.consumer.com.au
      - CORE_PEER_ADDRESS=peer1.consumer.com.au:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.com.au:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.com.au:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.com.au/peers/peer1.consumer.com.au/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.com.au/peers/peer1.consumer.com.au/tls:/etc/hyperledger/fabric/tls
        - peer1.consumer.com.au:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
