# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  clyde-orderer.clyde.com.au:
  peer0.producer.com.au:
  peer1.producer.com.au:
  peer0.consumer.com.au:
  peer1.consumer.com.au:

networks:
  clyde:

services:

  clyde-orderer.clyde.com.au:
    extends:
      file:   base/docker-compose-base.yaml
      service: clyde-orderer.clyde.com.au
    container_name: clyde-orderer.clyde.com.au
    networks:
      - clyde

  peer0.producer.com.au:
    container_name: peer0.producer.com.au
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.producer.com.au
    networks:
      - clyde

  peer1.producer.com.au:
    container_name: peer1.producer.com.au
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.producer.com.au
    networks:
      - clyde

  peer0.consumer.com.au:
    container_name: peer0.consumer.com.au
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.consumer.com.au
    networks:
      - clyde

  peer1.consumer.com.au:
    container_name: peer1.consumer.com.au
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.consumer.com.au
    networks:
      - clyde

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.producer.com.au:7051
      - CORE_PEER_LOCALMSPID=Producer-MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com.au/peers/peer0.producer.com.au/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com.au/peers/peer0.producer.com.au/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com.au/peers/peer0.producer.com.au/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com.au/users/Admin@producer.com.au/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - clyde-orderer.clyde.com.au
      - peer0.producer.com.au
      - peer1.producer.com.au
      - peer0.consumer.com.au
      - peer1.consumer.com.au
    networks:
      - clyde
      