#-------------------------------------------------------------------------------
#
#   CAPABILITIES
#
#-------------------------------------------------------------------------------

Capabilities:

    Global: &ChannelCapabilities
        V1_4: true

    Orderer: &OrdererCapabilities
        V1_4: true

    Application: &ApplicationCapabilities
        V1_4: true

#-------------------------------------------------------------------------------
#    Organisations
#-------------------------------------------------------------------------------

Organizations:

    - &Clyde-Orderer
        #-----------------------------------------------------------------------
        #    'Clyde-Orderer' is the orderer reference for this organisation.
        #-----------------------------------------------------------------------
        Name:           Clyde-Orderer
        ID:             Clyde-Orderer-MSP
        MSPDIR:         '/Users/ed/Dropbox/Development/Blockchains/Hyperledger/Clyde Green Roof/Clyde-Prototype-III/crypto-config/ordererOrganizations/clyde.com/orderers/clyde-orderer.clyde.com/msp'
        Policies:
          Readers:
              Type: Signature
              Rule: "OR('clyde-orderer.clyde.com.member')"
          Writers:
              Type: Signature
              Rule: "OR('clyde-orderer.clyde.com.member')"
          Admins:
              Type: Signature
              Rule: "OR('clyde-orderer.clyde.com.admin')"

    - &Clyde
        #-----------------------------------------------------------------------
        #    'Clyde' is the channel reference for this organisation.
        #-----------------------------------------------------------------------
        Name:           Clyde
        ID:             Clyde-MSP
        MSPDir:         '/Users/ed/Dropbox/Development/Blockchains/Hyperledger/Clyde Green Roof/Clyde-Prototype-III/crypto-config/peerOrganizations/clyde.com/msp'
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.clyde.com
              Port: 7051
        Policies:
          Readers:
              Type: Signature
              Rule: "OR('peer0.clyde.com.member')"
          Writers:
              Type: Signature
              Rule: "OR('peer0.clyde.com.member')"
          Admins:
              Type: Signature
              Rule: "OR('peer0.clyde.com.admin')"

    - &UOM
        #-----------------------------------------------------------------------
        #    'UOM' is the channel reference for this organisation.
        #-----------------------------------------------------------------------
        Name:           UOM
        ID:             UOM-MSP
        MSPDir:         '/Users/ed/Dropbox/Development/Blockchains/Hyperledger/Clyde Green Roof/Clyde-Prototype-III/crypto-config/peerOrganizations/uom.com/msp'
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host:     peer0.uom.com
              Port:     8051
        Policies:
          Readers:
              Type: Signature
              Rule: "OR('peer0.uom.com.member')"
          Writers:
              Type: Signature
              Rule: "OR('peer0.uom.com.member')"
          Admins:
              Type: Signature
              Rule: "OR('peer0.uom.com.admin')"

    - &Penta
        #-----------------------------------------------------------------------
        #    'Penta' is the channel reference for this organisation.
        #-----------------------------------------------------------------------
        Name:           Penta
        ID:             Penta-MSP
        MSPDir:         '/Users/ed/Dropbox/Development/Blockchains/Hyperledger/Clyde Green Roof/Clyde-Prototype-III/crypto-config/peerOrganizations/penta.com/msp'
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host:     peer0.penta.com
              Port:     9051
        Policies:
          Readers:
              Type: Signature
              Rule: "OR('peer0.penta.com.member')"
          Writers:
              Type: Signature
              Rule: "OR('peer0.penta.com.member')"
          Admins:
              Type: Signature
              Rule: "OR('peer0.penta.com.admin')"

#-------------------------------------------------------------------------------
#   Orderer:
#   Ideally, we would like to have each organsiation in control of of its own
#   ordering service. However, this does not seem to be possible in the current
#   incarnation of Hyperledger - so for now its a solo orderer. When we move to
#   AMAZON or Azure then we will move to a cluster orderer and Kafka. Note that
#   a cluster is controled by one organsiation and not a decentralised soln.
#-------------------------------------------------------------------------------

Orderer: &OrdererPolicies
    OrdererType: solo
    Addresses:
        - clyde-orderer.clyde.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch.
    BatchTimeout: 10s

    # Batch Size: Controls the number of messages batched into a block.
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB

    MaxChannels: 0

    Organizations:

    Policies:
      Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"

      Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"

      Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"

      BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"

    Kafka:
      Brokers:
          - kafka0:9092
          - kafka1:9092
          - kafka2:9092
          - kafka3:9092

    Capabilities:
        <<: *OrdererCapabilities

#-------------------------------------------------------------------------------
#
#   CHANNEL
#
#-------------------------------------------------------------------------------

Channel: &ChannelPolicies
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

#-------------------------------------------------------------------------------
#    Applications:
#    Organizations lists the orgs participating on the application side of the
#    network.
#-------------------------------------------------------------------------------

Application: &ApplicationPolicies
    Organizations:
      - *Clyde
      - *UOM
      - *Penta

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    # Capabilities describes the application level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ApplicationCapabilities

#-------------------------------------------------------------------------------
#
#   PROFILES
#
#-------------------------------------------------------------------------------

Profiles:

   #---------- Genesis Block Configuration -------------------------------------

    Clyde-Green-Roof-Genesis:
        <<: *ChannelPolicies

        Orderer:
            <<: *OrdererPolicies
            Organizations:
                - <<: *Clyde-Orderer
                  AdminPrincipal: Role.ADMIN
            Capabilities:
                <<: *OrdererCapabilities

        Application:
            <<: *ApplicationPolicies
            Organizations:
                - *Clyde
                - *Penta
                - *UOM
            Capabilities:
                <<: *ApplicationCapabilities

        Consortiums:
            Clyde-Consortium:
                Organizations:
                    - <<: *Clyde
                    - <<: *Penta
                    - <<: *UOM

   #---------- Channel Configuration -------------------------------------------

    Clyde-Green-Roof-Channel:
        Consortium: Clyde-Consortium
        Orderer:
            <<: *OrdererPolicies
            Organizations:
                - <<: *Clyde-Orderer
                  AdminPrincipal: Role.ADMIN
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationPolicies
            Organizations:
                - *Clyde
                - *UOM
                - *Penta
            Capabilities:
                <<: *ApplicationCapabilities
