version: '2'

#--------------------------------------------------------------------------------------
#
#  Clyde Network
#  Create and execute the network
#  Ed. Kazmierczak
#  Based on Hyperledger Examples BYFN docker-comose-cli examle and basic-network.
#
#-------------------------------------------------------------------------------------

volumes:
  clyde-consortium.clyde.com:
  peer0.clyde.com:
  peer1.clyde.com:
  peer2.clyde.com:
  peer0.uom.com:
  peer1.uom.com:
  peer2.uom.com:
  peer0.penta.com:
  peer1.penta.com:
  peer2.penta.com:

networks:
  clyde-green-roof:

services:

  clyde-consortium.clyde.com:
    extends:
      file:   base/docker-clyde-network-base.yaml
      service: clyde-consortium.clyde.com
    container_name: clyde-consortium.clyde.com
    networks:
      - clyde-green-roof

  peer0.clyde.com:
    container_name: peer0.clyde.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer0.clyde.com
    networks:
      - clyde-green-roof

  peer1.clyde.com:
    container_name: peer1.clyde.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer1.clyde.com
    networks:
      - clyde-green-roof

  peer2.clyde.com:
    container_name: peer2.clyde.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer2.clyde.com
    networks:
      - clyde-green-roof

  peer0.uom.com:
    container_name: peer0.uom.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer0.uom.com
    networks:
      - clyde-green-roof

  peer1.uom.com:
    container_name: peer1.uom.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer1.uom.com
    networks:
      - clyde-green-roof
      
  peer2.uom.com:
    container_name: peer2.uom.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer2.uom.com
    networks:
      - clyde-green-roof

  peer0.penta.com:
    container_name: peer0.penta.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer0.penta.com
    networks:
      - clyde-green-roof

  peer1.penta.com:
    container_name: peer1.penta.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer1.penta.com
    networks:
      - clyde-green-roof
      
  peer2.penta.com:
    container_name: peer2.penta.com
    extends:
      file:  base/docker-clyde-network-base.yaml
      service: peer2.penta.com
    networks:
      - clyde-green-roof

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.clyde.com:7051
      - CORE_PEER_LOCALMSPID=Clyde-MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clyde.com/peers/peer0.clyde.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clyde.com/peers/peer0.clyde.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clyde.com/peers/peer0.clyde.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clyde.com/users/Admin@clyde.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - clyde-consortium.clyde.com
      - peer0.clyde.com
      - peer1.clyde.com
      - peer2.clyde.com
      - peer0.uom.com
      - peer1.uom.com 
      - peer2.uom.com
      - peer0.penta.com
      - peer1.penta.com
      - peer2.penta.com
    networks:
      - clyde-green-roof
      